### ISSUE TITLE
On Behalf Of for a Membesrhip, should  be Person to Organization relationship

### ISSUE THREAD

**Issue by kaerumy** [Sinar/popit_relationship#20]
eg. Azmin Ali (Person) is a member of Parliament (Organization) on behalf of Bersatu (Organization)

![image](https://user-images.githubusercontent.com/1060743/87240288-e6619400-c44a-11ea-9c36-4077a83a85c2.png)

In this example, Rais Husin (Person) is Chairman of MDEC (Organization) OnBehalfOf Bersatu (Organization)

**Comment by kaerumy** [comment]
This might not be a bug.. that Membership was on behalf of Bersatu..

**Comment by Jeffrey04** [comment]
according to the spec, the `opengov:onbehalfof` property is bound to the membership itself, not to the person
https://www.popoloproject.com/specs/membership.html

**Comment by kaerumy** [comment]
Closing as invalid, for Memberships we will need to keep the context of multiple relationships
