### ISSUE TITLE
subOrganization of doesn't seem to be a relationship between Orgnanizations

### ISSUE THREAD

**Issue by kaerumy** [Sinar/popit_relationship#21]
![image](https://user-images.githubusercontent.com/1060743/87240658-06df1d80-c44e-11ea-87a3-81116959cd33.png)

**Comment by Jeffrey04** [comment]
hmm, the grey node is a duplicate, it shouldn't be there, lemme see if i find a quick fix

**Comment by Jeffrey04** [comment]
ok I get it now, because I didn't specify the type for the destination end of arrow (due to lack of readily available information), so you see Chairman (of type `Membership`) points to both `FELDA` (type `Organization`) and a blank node in grey (type not specified).

**Comment by Jeffrey04** [comment]
the problem should be fixed now with the updated node saving code
