### ISSUE TITLE
A lot of the requirements in requirements.txt are oudated

### ISSUE THREAD

**Issue by lowks** [Sinar/popit_relationship#3]
A lot of the requirements in requirements.txt are oudated, some have new names and some do not exists anymore

**Comment by sweemeng** [comment]
Interesting. the script is not that old, and I run it not that long ago. I recheck my environment and update it Pretty important as this will be part of the next big project...

**Comment by lowks** [comment]
So, you rechecked it and it's okay ? I looked up `bulb` for example on `pypi` and it's not even there replaced by something called `lightbulb`

**Comment by sweemeng** [comment]
I verified in a new empty virtualenv. Removed a number of requirement for this project

**Comment by lowks** [comment]
Thank you. Let me try


[image: Low Kian Seong on about.me]

Low Kian Seong
about.me/lowkianseong
  <http://about.me/lowkianseong>

**Comment by lowks** [comment]
This works now. I just updated the `README.md` for some additional steps
