### ISSUE TITLE
Subordinate relationship is subordinate/superior based on position not employment

### ISSUE THREAD

**Issue by kaerumy** [Sinar/popit_relationship#30]
![image](https://user-images.githubusercontent.com/1060743/88184118-e8a2ca00-cc64-11ea-9559-1e5495511296.png)

**Comment by kaerumy** [comment]
In this case Ong Kian Ming is subordinate of Lim Guan Eng, by position, but not employed by LGE.

Like team leader and team member. Team member is not necessarily the employee of Team Leader

**Comment by Jeffrey04** [comment]
should I just use the generic Relationship instead? can't find anything equivalent

**Comment by Jeffrey04** [comment]
fixed in the merged code, try again?

**Comment by Jeffrey04** [comment]
example search

```
match (a:Person)-[:Relationship {name="subordinate"}]->(b:Person)
return a, b
```
