### ISSUE TITLE
Match relationship categories in Politikus (business partner, associate, romantic)

### ISSUE THREAD

**Issue by kaerumy** [Sinar/popit_relationship#33]
![image](https://user-images.githubusercontent.com/1060743/88492910-d4eac100-cfe0-11ea-8ffb-376962667e4c.png)

Instead of collaboratesWith, the relationship needs to be more specific as defined in relationship category

 * businessPartner
 * associate
 * romantic

There are editorial and legal implications of not differentiating associate vs business partner.

**Comment by Jeffrey04** [comment]
Currently the type of a relationship between Person is deduced here https://github.com/Sinar/popit_relationship/blob/master/src/popit_relationship/sync.py#L192 based on the `token` assigned

So if there are other new token that I can map to the relationship schema, I will add new entries to the mapping. As of now, even if the relationship is not handled, you can still query them as the original relationship `token` is stored as property

```
match (a:Person)-[rel {name: "romantic"}]->(b:Person) return a, b
```
