### ISSUE TITLE
https://politikus.sinarproject.org/@search is down

### ISSUE THREAD

**Issue by huseinzol05** [Sinar/popit_relationship#44]
hopefully everything is up back, thanks!

**Comment by arky** [comment]
@Jeffrey04   @kaerumy Confirmed, Can you please look into this. Thanks!

**Comment by kaerumy** [comment]
It's back up. The hosting server rebooted for some reason.

**Comment by arky** [comment]
Thanks @kaerumy

**Comment by huseinzol05** [comment]
thanks!
